// metal_shaders.h — MSL source for the M1 passthrough pipeline, compiled at
// runtime via newLibraryWithSource (build-time .metallib is an M5 option).
#ifndef METAL_SHADERS_H
#define METAL_SHADERS_H

static const char *kMetalShaderSource =
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"\n"
"// Must match MetalScreenVertex in metal_internal.h (28 bytes).\n"
"struct VSIn {\n"
"    packed_float3 pos;\n"
"    packed_float3 uvw;     // (u*invW, v*invW, invW); w==1 for sprites\n"
"    uchar4        color;\n"
"};\n"
"\n"
"struct VSOut {\n"
"    float4 position [[position]];\n"
"    float3 uvw;\n"
"    float4 color;\n"
"    float  fogDepth;\n"
"};\n"
"\n"
"vertex VSOut oni_vertex(const device VSIn *verts [[buffer(0)]],\n"
"                        constant float2 &screen  [[buffer(1)]],\n"
"                        uint vid                 [[vertex_id]])\n"
"{\n"
"    VSIn v = verts[vid];\n"
"    VSOut out;\n"
"    // glOrtho(0, w, h, 0, 0, 1) + ZCOORD double-negation == this mapping:\n"
"    // x: 0..w -> -1..1, y: 0..h -> 1..-1 (flip), z: 0..1 passthrough.\n"
"    out.position = float4(v.pos.x * (2.0f / screen.x) - 1.0f,\n"
"                          1.0f - v.pos.y * (2.0f / screen.y),\n"
"                          v.pos.z, 1.0f);\n"
"    out.uvw   = float3(v.uvw);\n"
"    out.color = float4(v.color) * (1.0f / 255.0f);\n"
"    out.fogDepth = v.pos.z;\n"
"    return out;\n"
"}\n"
"\n"
"// Must match MetalFogUniform in metal_internal.h (24 bytes).\n"
"struct FogU {\n"
"    float4 color;    // rgb = fog colour, a = enabled (0/1)\n"
"    float2 range;    // (start, end) in screen-space z\n"
"};\n"
"\n"
"fragment float4 oni_fragment(VSOut in              [[stage_in]],\n"
"                             texture2d<float> tex0 [[texture(0)]],\n"
"                             sampler          samp0 [[sampler(0)]],\n"
"                             constant FogU   &fog  [[buffer(0)]])\n"
"{\n"
"    // Hyperbolic texturing: linear-in-screen-space interpolation of\n"
"    // (u/w, v/w, 1/w), divided per fragment == GL's glTexCoord4f q path.\n"
"    float2 uv = in.uvw.xy / in.uvw.z;\n"
"    float4 c = tex0.sample(samp0, uv) * in.color;\n"
"    if (fog.color.a > 0.5f) {\n"
"        // GL_LINEAR: f = clamp((end - z)/(end - start), 0, 1); 1 = clear, 0 = full fog.\n"
"        float denom = fog.range.y - fog.range.x;\n"
"        float f = (denom != 0.0f) ? clamp((fog.range.y - in.fogDepth) / denom, 0.0f, 1.0f) : 1.0f;\n"
"        c.rgb = mix(fog.color.rgb, c.rgb, f);   // fog after texture x colour; alpha untouched\n"
"    }\n"
"    return c;\n"
"}\n"
"\n"
"// ---- M3 environment-map combine -------------------------------------------\n"
"// Must match MetalEnvVertex in metal_internal.h (40 bytes).\n"
"struct EnvVSIn {\n"
"    packed_float3 pos;\n"
"    packed_float3 buvw;    // base (u*invW, v*invW, invW)\n"
"    packed_float3 euvw;    // env  (u*invW, v*invW, invW)\n"
"    uchar4        color;\n"
"};\n"
"\n"
"struct EnvVSOut {\n"
"    float4 position [[position]];\n"
"    float3 buvw;\n"
"    float3 euvw;\n"
"    float4 color;\n"
"    float  fogDepth;\n"
"};\n"
"\n"
"vertex EnvVSOut oni_env_vertex(const device EnvVSIn *verts [[buffer(0)]],\n"
"                               constant float2 &screen     [[buffer(1)]],\n"
"                               uint vid                     [[vertex_id]])\n"
"{\n"
"    EnvVSIn v = verts[vid];\n"
"    EnvVSOut out;\n"
"    out.position = float4(v.pos.x * (2.0f / screen.x) - 1.0f,\n"
"                          1.0f - v.pos.y * (2.0f / screen.y),\n"
"                          v.pos.z, 1.0f);\n"
"    out.buvw   = float3(v.buvw);\n"
"    out.euvw   = float3(v.euvw);\n"
"    out.color  = float4(v.color) * (1.0f / 255.0f);\n"
"    out.fogDepth = v.pos.z;\n"
"    return out;\n"
"}\n"
"\n"
"// texEnv = reflection map (GL TEXTURE0), texBase = base map (GL TEXTURE1).\n"
"// GL net (two-pass on this Mac): diffuse * (base.rgb + env.rgb * base.alpha),\n"
"// opaque. base.alpha is the shininess mask. (gl_geometry_draw_method.c:164-251,\n"
"// Motoko_Geom.c:200-243, gl_utility.c:2023.)\n"
"fragment float4 oni_env_fragment(EnvVSOut in              [[stage_in]],\n"
"                                 texture2d<float> texEnv  [[texture(0)]],\n"
"                                 sampler          sampEnv [[sampler(0)]],\n"
"                                 texture2d<float> texBase [[texture(1)]],\n"
"                                 sampler          sampBase[[sampler(1)]],\n"
"                                 constant FogU   &fog     [[buffer(0)]])\n"
"{\n"
"    float2 buv = in.buvw.xy / in.buvw.z;\n"
"    float2 euv = in.euvw.xy / in.euvw.z;\n"
"    float4 base = texBase.sample(sampBase, buv);\n"
"    float4 env  = texEnv.sample(sampEnv, euv);\n"
"    float3 rgb  = (base.rgb + env.rgb * base.a) * in.color.rgb;\n"
"    float4 c    = float4(rgb, in.color.a);\n"
"    if (fog.color.a > 0.5f) {\n"
"        float denom = fog.range.y - fog.range.x;\n"
"        float f = (denom != 0.0f) ? clamp((fog.range.y - in.fogDepth) / denom, 0.0f, 1.0f) : 1.0f;\n"
"        c.rgb = mix(fog.color.rgb, c.rgb, f);\n"
"    }\n"
"    return c;\n"
"}\n";

#endif // METAL_SHADERS_H
