#!/usr/bin/env bash
# check-sweep-byte-identity.sh — proves the level sweep harness (issue #103)
# has not changed the shipping Oni binary.
#
# The sweep needs hooks in files the shipping build also compiles: a macro call
# in COrConsole_Print, a widened #if, a warning tap in UUrPrintWarning. Those
# are meant to vanish when ONI_SWEEP_CONSOLE is not defined. "Meant to" is not
# evidence, and the property is easy to break by accident — BFW_Console.c bakes
# __LINE__ into its UUmError_Return* call sites, so merely adding a line above
# them changes the binary even when the code is unreachable.
#
# Method: build Oni twice on ONE unchanged CMake configure, once with the sweep
# hook files reverted to a reference commit and once with them present, and cmp
# the results. Holding the configure fixed matters — ONI_BUILD_STAMP and
# ONI_BUILD_EPOCH are regenerated by every cmake run, so any reconfigure
# changes three objects on its own and would mask or fake a result.
#
# Usage: scripts/check-sweep-byte-identity.sh [ref] [build-dir]
#   ref        commit/tree-ish holding the pre-sweep version of the hook files
#              (default: the merge-base with main)
#   build-dir  default: build
#
# Exit 0 identical, 1 differs, 2 setup problem.
set -u

REF="${1:-}"
BUILD="${2:-build}"

HOOK_FILES="
BungieFrameWork/BFW_Source/BFW_Console/BFW_Console.c
BungieFrameWork/BFW_Headers/BFW_Console.h
BungieFrameWork/BFW_Source/BFW_Utility/BFW_Error.c
BungieFrameWork/BFW_Headers/BFW.h
"

if [ ! -d "$BUILD" ]; then
	echo "no build directory at $BUILD"
	exit 2
fi

if [ -z "$REF" ]; then
	REF=$(git merge-base HEAD main 2>/dev/null) || {
		echo "could not determine a reference commit; pass one explicitly"
		exit 2
	}
fi

for f in $HOOK_FILES; do
	if ! git cat-file -e "$REF:$f" 2>/dev/null; then
		echo "reference $REF does not contain $f"
		exit 2
	fi
done

# Anything uncommitted in the hook files would be destroyed by the checkout
# below, so refuse rather than eat someone's work in progress.
if ! git diff --quiet -- $HOOK_FILES; then
	echo "hook files have uncommitted changes; commit or stash them first:"
	git --no-pager diff --stat -- $HOOK_FILES
	exit 2
fi

TMP=$(mktemp -d)
trap 'git checkout -- '"$HOOK_FILES"' 2>/dev/null; rm -rf "$TMP"' EXIT

echo "reference: $REF"
echo "build dir: $BUILD"
echo

echo "[1/2] building Oni with the sweep hooks reverted..."
git checkout "$REF" -- $HOOK_FILES || { echo "checkout failed"; exit 2; }
cmake --build "$BUILD" --target Oni -j8 > "$TMP/build1.log" 2>&1 || {
	echo "build failed:"; tail -20 "$TMP/build1.log"; exit 2; }
cp "$BUILD/bin/Oni" "$TMP/Oni.reference"

echo "[2/2] building Oni with the sweep hooks present..."
git checkout HEAD -- $HOOK_FILES || { echo "checkout failed"; exit 2; }
cmake --build "$BUILD" --target Oni -j8 > "$TMP/build2.log" 2>&1 || {
	echo "build failed:"; tail -20 "$TMP/build2.log"; exit 2; }

echo
echo "  without hooks: $(shasum -a 256 "$TMP/Oni.reference" | awk '{print $1}')"
echo "  with hooks   : $(shasum -a 256 "$BUILD/bin/Oni" | awk '{print $1}')"
echo

if cmp -s "$TMP/Oni.reference" "$BUILD/bin/Oni"; then
	echo "OK — the shipping binary is byte-identical with and without the sweep hooks."
	exit 0
fi

echo "CHANGED — the shipping binary is not the same."
echo
echo "Note: reverting the hook files also reverts anything else those files carry."
echo "As of #103 that includes one deliberate shipping change — COrConsole_Printf,"
echo "COrConsole_Printf_Color, SLrScript_ReportError and SLrScript_DisplayError were"
echo "converted from vsprintf to vsnprintf. A delta confined to BFW_Console.c.o and"
echo "BFW_ScriptLang_Error.c.o is that, and is expected."
echo
echo "Object-level delta:"
ONI_DIR="$BUILD/OniProj/OniCMakeProjs/OniProj/CMakeFiles/Oni.dir"
if [ -d "$ONI_DIR" ]; then
	find "$ONI_DIR" -name '*.o' | sort | xargs shasum -a 256 > "$TMP/after.txt"
	# rebuild the reference side's object hashes for comparison
	git checkout "$REF" -- $HOOK_FILES 2>/dev/null
	cmake --build "$BUILD" --target Oni -j8 > "$TMP/build3.log" 2>&1
	find "$ONI_DIR" -name '*.o' | sort | xargs shasum -a 256 > "$TMP/before.txt"
	git checkout HEAD -- $HOOK_FILES 2>/dev/null
	cmake --build "$BUILD" --target Oni -j8 > "$TMP/build4.log" 2>&1
	diff "$TMP/before.txt" "$TMP/after.txt" | grep '^<' | sed 's#.*CMakeFiles/Oni.dir/#  #' || true
fi
echo
echo "Any object outside that expected pair is an accident. The usual cause is a"
echo "physical line added above a __LINE__ user in BFW_Console.c or BFW_Error.c:"
echo "disassemble the differing .o and look for 'mov' immediates that shifted by"
echo "the number of lines added."
exit 1
